server:
  port: 8081

spring:
  application:
    name: diagram-parser-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  dynamodb:
    table:
      diagrams: diagrams

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      cloudwatch:
        enabled: true
        namespace: EdgeConvert/DiagramParser

logging:
  level:
    com.edgeconvert: DEBUG
    software.amazon.awssdk: INFO